apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd
  - authentik
  - backstage
  - cilium
  - cloudflare
  - cnpg-operator
  - external-secrets-operator
  - headlamp
  - local-path-provisioner
  - metallb
  - metallb-config
  - metrics-server
  - monitoring
  - nfs-provisioner
  - skyhook-connector
  - tailscale
  - vault
