apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd
  - cloudflare
  - external-secrets-operator
  - headlamp
  - metallb
  - metallb-config
  - metrics-server
  - nfs-provisioner
  - tailscale
  - vault
