apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rexireports-dev

resources:
  - ../../../base/rexireports/base
  - ingress.yaml

replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1

images:
  - name: operez11/rexi-reports-backend
    newTag: "dev-latest"
  - name: operez11/rexi-reports-frontend
    newTag: "dev-latest"
