apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-demo
  namespace: argo-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/OPerezSandoval/homelab-gitops.git
    targetRevision: main
    path: kubernetes/apps/overlays/dev/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true