apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archeflow-site-dev
  namespace: argo-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/OPerezSandoval/homelab-gitops.git
    targetRevision: main
    path: kubernetes/apps/overlays/dev/archeflow-site
  destination:
    server: https://kubernetes.default.svc
    namespace: archeflow-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: archeflow-site-prod
  namespace: argo-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/OPerezSandoval/homelab-gitops.git
    targetRevision: main
    path: kubernetes/apps/overlays/prod/archeflow-site
  destination:
    server: https://kubernetes.default.svc
    namespace: archeflow-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
