apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medtracker-dev

resources:
- ../../../base/medtracker/base
- pvc.yaml
- ingress.yaml
- external-secret.yaml

replicas:
- count: 1
  name: medtracker

images:
- name: operez11/medtracker
  newTag: dev-a200ad6
