apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argo-gitops
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.78.3
      helm:
        values: |
          oauth:
            clientIdFromSecret: true
            clientSecretFromSecret: true
          operatorConfig:
            hostname: "tailscale-operator"
    - repoURL: https://github.com/OPerezSandoval/homelab-gitops.git
      targetRevision: main
      path: kubernetes/infra/tailscale/extras
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
