apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: archeflow-prod

resources:
  - ../../../base/archeflow-site/base
  - ingress.yaml

replicas:
  - name: archeflow-site
    count: 2

images:
  - name: operez11/archeflow-site
    newTag: "v0.1.0"
