apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare
  namespace: cloudflare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare
  template:
    metadata:
      labels:
        app: cloudflare
    spec:
      containers:
        - name: cloudflare
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secrets
                  key: tunnel-token
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 512Mi