apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metallb-config
  - tailscale
  - helm-demo
  - kustomize-demo
  - medtracker
  - vault
  - external-secrets-operator
  - n8n
  - archeflow-site
